from .api_views.account import *
from .api_views.notification import *
from .api_views.group import *
from .api_views.question import *
from .api_views.exam import *
from .api_views.like import *
from .api_views.comment import *
from .api_views.classify import *
from tests.test import *
from .api_views.storage import *
from .api_views.user import *